export type EmojiCategoryId = 'recent' | 'smileys' | 'gestures' | 'animals' | 'food' | 'activities' | 'travel' | 'objects' | 'symbols';

export type EmojiEntry = { emoji: string; label: string; keywords: string[]; category: Exclude<EmojiCategoryId, 'recent'> };

type RawEmoji = [emoji: string, label: string, ...keywords: string[]];

const define = (category: EmojiEntry['category'], entries: RawEmoji[]): EmojiEntry[] =>
  entries.map(([emoji, label, ...keywords]) => ({ emoji, label, keywords, category }));

export const EMOJI_CATEGORIES: Array<{ id: EmojiCategoryId; icon: string; label: string }> = [
  { id: 'recent', icon: '◷', label: 'Recentes' },
  { id: 'smileys', icon: '😀', label: 'Rostos' },
  { id: 'gestures', icon: '👋', label: 'Gestos' },
  { id: 'animals', icon: '🐶', label: 'Animais' },
  { id: 'food', icon: '🍔', label: 'Comida' },
  { id: 'activities', icon: '⚽', label: 'Atividades' },
  { id: 'travel', icon: '✈️', label: 'Viagem' },
  { id: 'objects', icon: '💡', label: 'Objetos' },
  { id: 'symbols', icon: '❤️', label: 'Símbolos' },
];

export const EMOJI_CATALOG: EmojiEntry[] = [
  ...define('smileys', [
    ['😀', 'Rosto sorridente', 'feliz', 'sorriso', 'grin'], ['😃', 'Rosto sorridente com boca aberta', 'feliz', 'alegre'], ['😄', 'Rosto sorrindo com olhos felizes', 'feliz', 'risada'], ['😁', 'Rosto mostrando os dentes', 'sorriso', 'riso'], ['😆', 'Rosto rindo', 'risada', 'haha'], ['😅', 'Rosto sorrindo com suor', 'alívio', 'nervoso'], ['😂', 'Rosto com lágrimas de alegria', 'rir', 'kkk', 'lol'], ['🤣', 'Rolando de rir', 'risada', 'haha'], ['😊', 'Rosto sorridente com olhos felizes', 'fofo', 'feliz'], ['😇', 'Rosto sorridente com auréola', 'anjo', 'inocente'], ['🙂', 'Rosto levemente sorridente', 'sorriso'], ['🙃', 'Rosto de cabeça para baixo', 'ironia'], ['😉', 'Piscadinha', 'olho', 'flertar'], ['😍', 'Rosto apaixonado', 'amor', 'coração'], ['🥰', 'Rosto sorridente com corações', 'amor', 'paixão'], ['😘', 'Beijo', 'amor', 'coração'], ['😋', 'Rosto saboreando comida', 'delícia'], ['😎', 'Rosto com óculos escuros', 'legal', 'cool'], ['🤩', 'Rosto encantado', 'estrela', 'uau'], ['🥳', 'Rosto comemorando', 'festa', 'aniversário'], ['😏', 'Sorriso malicioso', 'safado'], ['😒', 'Rosto descontente', 'tédio'], ['😔', 'Rosto pensativo', 'triste'], ['😢', 'Rosto chorando', 'tristeza'], ['😭', 'Rosto chorando alto', 'lágrimas', 'triste'], ['😡', 'Rosto bravo', 'raiva'], ['🤬', 'Rosto xingando', 'raiva'], ['😱', 'Rosto gritando de medo', 'surpresa', 'medo'], ['😨', 'Rosto assustado', 'medo'], ['🤔', 'Rosto pensando', 'dúvida'], ['🤗', 'Rosto abraçando', 'abraço'], ['🤭', 'Rosto com mão na boca', 'ops'], ['🫡', 'Rosto saudando', 'respeito'], ['😴', 'Rosto dormindo', 'sono'], ['🤮', 'Rosto vomitando', 'doente'], ['🤯', 'Cabeça explodindo', 'mente', 'uau'], ['🥺', 'Rosto implorando', 'por favor'], ['😈', 'Rosto sorridente com chifres', 'diabo'], ['💀', 'Caveira', 'morte'], ['🤡', 'Palhaço', 'engraçado'], ['👻', 'Fantasma', 'terror'], ['💩', 'Cocô', 'merda'], ['🤖', 'Robô', 'bot', 'ia'], ['🎃', 'Abóbora', 'halloween'],
  ]),
  ...define('gestures', [
    ['👋', 'Mão acenando', 'oi', 'tchau'], ['🤚', 'Mão levantada', 'pare'], ['🖐️', 'Mão aberta', 'cinco'], ['✋', 'Mão levantada', 'pare'], ['🫱', 'Mão direita', 'mão'], ['🫲', 'Mão esquerda', 'mão'], ['👌', 'Sinal de ok', 'ok', 'perfeito'], ['🤌', 'Dedos juntos', 'italiano'], ['🤏', 'Mão pinçando', 'pequeno'], ['✌️', 'Sinal de paz', 'vitória'], ['🤞', 'Dedos cruzados', 'sorte'], ['🫰', 'Coração com dedos', 'amor'], ['🤟', 'Eu te amo', 'amor'], ['🤘', 'Sinal de rock', 'rock'], ['🤙', 'Me liga', 'telefone'], ['👈', 'Dedo apontando esquerda', 'esquerda'], ['👉', 'Dedo apontando direita', 'direita'], ['👆', 'Dedo apontando acima', 'cima'], ['👇', 'Dedo apontando abaixo', 'baixo'], ['☝️', 'Dedo indicador', 'um'], ['👍', 'Polegar para cima', 'like', 'sim'], ['👎', 'Polegar para baixo', 'dislike', 'não'], ['✊', 'Punho fechado', 'força'], ['👊', 'Soquinho', 'punho'], ['🤝', 'Aperto de mãos', 'acordo'], ['👏', 'Palmas', 'aplauso'], ['🙌', 'Mãos levantadas', 'comemorar'], ['👐', 'Mãos abertas', 'abraço'], ['🤲', 'Palmas para cima', 'pedido'], ['🙏', 'Mãos juntas', 'obrigado', 'por favor'], ['✍️', 'Escrevendo', 'caneta'], ['💅', 'Esmalte', 'unha'], ['🤳', 'Selfie', 'foto'], ['💪', 'Braço forte', 'força'], ['🫶', 'Mãos formando coração', 'amor'], ['🫂', 'Pessoas abraçando', 'abraço'],
  ]),
  ...define('animals', [
    ['🐶', 'Cachorro', 'cão', 'pet'], ['🐱', 'Gato', 'gatinho', 'pet'], ['🐭', 'Rato', 'mouse'], ['🐹', 'Hamster', 'pet'], ['🐰', 'Coelho', 'bunny'], ['🦊', 'Raposa', 'fox'], ['🐻', 'Urso', 'bear'], ['🐼', 'Panda', 'urso'], ['🐨', 'Coala', 'austrália'], ['🐯', 'Tigre', 'felino'], ['🦁', 'Leão', 'rei'], ['🐮', 'Vaca', 'fazenda'], ['🐷', 'Porco', 'fazenda'], ['🐸', 'Sapo', 'frog'], ['🐵', 'Macaco', 'monkey'], ['🐔', 'Galinha', 'frango'], ['🐧', 'Pinguim', 'frio'], ['🐦', 'Pássaro', 'ave'], ['🦄', 'Unicórnio', 'magia'], ['🐝', 'Abelha', 'inseto'], ['🦋', 'Borboleta', 'inseto'], ['🐢', 'Tartaruga', 'lento'], ['🐍', 'Cobra', 'serpente'], ['🦖', 'Dinossauro', 'dino'], ['🐙', 'Polvo', 'mar'], ['🦈', 'Tubarão', 'mar'], ['🐬', 'Golfinho', 'mar'], ['🐳', 'Baleia', 'mar'], ['🐠', 'Peixe', 'aquário'], ['🐊', 'Crocodilo', 'jacaré'],
  ]),
  ...define('food', [
    ['🍏', 'Maçã verde', 'fruta'], ['🍎', 'Maçã vermelha', 'fruta'], ['🍐', 'Pera', 'fruta'], ['🍊', 'Laranja', 'fruta'], ['🍋', 'Limão', 'fruta'], ['🍌', 'Banana', 'fruta'], ['🍉', 'Melancia', 'fruta'], ['🍇', 'Uva', 'fruta'], ['🍓', 'Morango', 'fruta'], ['🫐', 'Mirtilo', 'fruta'], ['🍈', 'Melão', 'fruta'], ['🍒', 'Cereja', 'fruta'], ['🍑', 'Pêssego', 'fruta'], ['🥭', 'Manga', 'fruta'], ['🍍', 'Abacaxi', 'fruta'], ['🥥', 'Coco', 'fruta'], ['🥑', 'Abacate', 'vegetal'], ['🍅', 'Tomate', 'vegetal'], ['🥕', 'Cenoura', 'vegetal'], ['🌽', 'Milho', 'vegetal'], ['🍔', 'Hambúrguer', 'lanche'], ['🍟', 'Batata frita', 'lanche'], ['🍕', 'Pizza', 'comida'], ['🌭', 'Cachorro-quente', 'lanche'], ['🥪', 'Sanduíche', 'lanche'], ['🌮', 'Taco', 'mexicano'], ['🍣', 'Sushi', 'japonês'], ['🍜', 'Lámen', 'macarrão'], ['🍝', 'Macarrão', 'massa'], ['🍰', 'Bolo', 'doce'], ['🎂', 'Bolo de aniversário', 'festa'], ['🍫', 'Chocolate', 'doce'], ['🍿', 'Pipoca', 'cinema'], ['☕', 'Café', 'bebida'], ['🍺', 'Cerveja', 'bebida'], ['🍻', 'Brinde com cervejas', 'festa'], ['🥂', 'Taças brindando', 'brinde'], ['🍷', 'Vinho', 'bebida'], ['🥤', 'Refrigerante', 'bebida'], ['💧', 'Gota de água', 'água'],
  ]),
  ...define('activities', [
    ['⚽', 'Bola de futebol', 'esporte'], ['🏀', 'Basquete', 'esporte'], ['🏈', 'Futebol americano', 'esporte'], ['⚾', 'Beisebol', 'esporte'], ['🎾', 'Tênis', 'esporte'], ['🏐', 'Vôlei', 'esporte'], ['🏉', 'Rugby', 'esporte'], ['🥏', 'Disco', 'frisbee'], ['🎱', 'Sinuca', 'jogo'], ['🏓', 'Tênis de mesa', 'ping pong'], ['🏸', 'Badminton', 'esporte'], ['🥊', 'Boxe', 'luta'], ['🥋', 'Karatê', 'luta'], ['🏆', 'Troféu', 'vitória'], ['🥇', 'Medalha de ouro', 'primeiro'], ['🎮', 'Videogame', 'jogo'], ['🎲', 'Dado', 'jogo'], ['🧩', 'Quebra-cabeça', 'jogo'], ['🎯', 'Alvo', 'meta'], ['🎳', 'Boliche', 'jogo'], ['🎸', 'Violão', 'música'], ['🎹', 'Teclado musical', 'música'], ['🥁', 'Bateria', 'música'], ['🎤', 'Microfone', 'cantar'], ['🎧', 'Fone de ouvido', 'música'], ['🎬', 'Claquete', 'filme'], ['🎨', 'Paleta de pintura', 'arte'], ['🎭', 'Máscaras', 'teatro'], ['🎪', 'Circo', 'show'], ['🎉', 'Confete', 'festa'], ['🎊', 'Bola de confete', 'comemorar'], ['🎁', 'Presente', 'gift'],
  ]),
  ...define('travel', [
    ['🚗', 'Carro', 'automóvel'], ['🚕', 'Táxi', 'carro'], ['🚌', 'Ônibus', 'transporte'], ['🚎', 'Trólebus', 'transporte'], ['🏎️', 'Carro de corrida', 'velocidade'], ['🚓', 'Carro de polícia', 'polícia'], ['🚑', 'Ambulância', 'emergência'], ['🚒', 'Caminhão de bombeiros', 'emergência'], ['🚚', 'Caminhão', 'entrega'], ['🚜', 'Trator', 'fazenda'], ['🏍️', 'Moto', 'motocicleta'], ['🚲', 'Bicicleta', 'bike'], ['🛴', 'Patinete', 'transporte'], ['✈️', 'Avião', 'viagem'], ['🛫', 'Decolagem', 'avião'], ['🛬', 'Pouso', 'avião'], ['🚀', 'Foguete', 'espaço'], ['🛸', 'Disco voador', 'ovni'], ['🚁', 'Helicóptero', 'voar'], ['🚢', 'Navio', 'barco'], ['⛵', 'Veleiro', 'barco'], ['🚤', 'Lancha', 'barco'], ['🏠', 'Casa', 'lar'], ['🏢', 'Prédio', 'escritório'], ['🏖️', 'Praia', 'férias'], ['🏝️', 'Ilha', 'férias'], ['🏔️', 'Montanha', 'natureza'], ['🌋', 'Vulcão', 'natureza'], ['🗺️', 'Mapa', 'localização'], ['🗽', 'Estátua da Liberdade', 'nova york'], ['🗼', 'Torre de Tóquio', 'japão'], ['🕌', 'Mesquita', 'religião'],
  ]),
  ...define('objects', [
    ['⌚', 'Relógio', 'hora'], ['📱', 'Celular', 'telefone'], ['💻', 'Notebook', 'computador'], ['⌨️', 'Teclado', 'computador'], ['🖥️', 'Monitor', 'computador'], ['🖨️', 'Impressora', 'documento'], ['🖱️', 'Mouse', 'computador'], ['💾', 'Disquete', 'salvar'], ['💿', 'CD', 'música'], ['📷', 'Câmera', 'foto'], ['📹', 'Câmera de vídeo', 'vídeo'], ['☎️', 'Telefone', 'ligar'], ['💡', 'Lâmpada', 'ideia'], ['🔦', 'Lanterna', 'luz'], ['🕯️', 'Vela', 'luz'], ['📚', 'Livros', 'estudo'], ['📖', 'Livro aberto', 'ler'], ['📝', 'Anotações', 'escrever'], ['📌', 'Alfinete', 'fixar'], ['📎', 'Clipe de papel', 'anexo'], ['✂️', 'Tesoura', 'cortar'], ['🔒', 'Cadeado', 'seguro'], ['🔑', 'Chave', 'senha'], ['🔨', 'Martelo', 'ferramenta'], ['🛠️', 'Ferramentas', 'construção'], ['🧰', 'Caixa de ferramentas', 'trabalho'], ['🧲', 'Ímã', 'magnetismo'], ['💊', 'Pílula', 'remédio'], ['🩺', 'Estetoscópio', 'médico'], ['🧪', 'Tubo de ensaio', 'ciência'], ['💰', 'Saco de dinheiro', 'grana'], ['💳', 'Cartão de crédito', 'pagamento'], ['💎', 'Diamante', 'joia'], ['📦', 'Caixa', 'pacote'], ['✉️', 'Envelope', 'email'], ['📩', 'Email chegando', 'mensagem'], ['🗑️', 'Lixeira', 'apagar'],
  ]),
  ...define('symbols', [
    ['❤️', 'Coração vermelho', 'amor'], ['🩷', 'Coração rosa', 'amor'], ['🧡', 'Coração laranja', 'amor'], ['💛', 'Coração amarelo', 'amor'], ['💚', 'Coração verde', 'amor'], ['🩵', 'Coração azul claro', 'amor'], ['💙', 'Coração azul', 'amor'], ['💜', 'Coração roxo', 'amor'], ['🖤', 'Coração preto', 'amor'], ['🩶', 'Coração cinza', 'amor'], ['🤍', 'Coração branco', 'amor'], ['🤎', 'Coração marrom', 'amor'], ['💔', 'Coração partido', 'triste'], ['❤️‍🔥', 'Coração em chamas', 'amor'], ['❣️', 'Exclamação de coração', 'amor'], ['💕', 'Dois corações', 'amor'], ['💞', 'Corações girando', 'amor'], ['💯', 'Cem pontos', 'perfeito'], ['💢', 'Símbolo de raiva', 'bravo'], ['💥', 'Colisão', 'explosão'], ['💫', 'Tontura', 'estrela'], ['💦', 'Gotas de suor', 'água'], ['💨', 'Correndo', 'vento'], ['🕳️', 'Buraco', 'vazio'], ['💬', 'Balão de fala', 'mensagem'], ['🗨️', 'Balão de fala esquerdo', 'chat'], ['👁️‍🗨️', 'Olho em balão de fala', 'testemunha'], ['🗯️', 'Balão de raiva', 'fala'], ['💭', 'Balão de pensamento', 'pensar'], ['💤', 'Sono', 'dormir'], ['✅', 'Marca de seleção', 'ok', 'sim'], ['❌', 'X', 'erro', 'não'], ['❗', 'Exclamação', 'atenção'], ['❓', 'Interrogação', 'pergunta'], ['⚠️', 'Aviso', 'alerta'], ['🚫', 'Proibido', 'não'], ['♻️', 'Reciclagem', 'sustentável'], ['🔞', 'Menores proibidos', 'idade'], ['🔔', 'Sino', 'notificação'], ['🔕', 'Sino silenciado', 'notificação'], ['⭐', 'Estrela', 'favorito'], ['✨', 'Brilhos', 'magia'], ['🔥', 'Fogo', 'quente'], ['🌟', 'Estrela brilhante', 'especial'], ['🌈', 'Arco-íris', 'cor'], ['☀️', 'Sol', 'dia'], ['🌙', 'Lua', 'noite'], ['⚡', 'Raio', 'energia'], ['☔', 'Guarda-chuva', 'chuva'], ['☁️', 'Nuvem', 'tempo'],
  ]),
];

export const EMOJI_BY_VALUE = new Map(EMOJI_CATALOG.map(entry => [entry.emoji, entry]));
